### ISSUE TITLE
failure to build

### ISSUE THREAD

**Issue by cpu-chromium** [swetland/traceviz#1]
work/src/traceviz$ make
g++ -std=c++11 -MMD -g -Wall -Wformat -Isrc -Ithird_party/imgui -Ithird_party/imgui/examples/libs/gl3w -Ithird_party/imgui/examples/opengl3_example `pkg-config --cflags glfw3` -c -o out/src/traceviz.o src/traceviz.cpp
Package glfw3 was not found in the pkg-config search path.
Perhaps you should add the directory containing `glfw3.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glfw3' found
cc -std=c11 -MMD -g -Wall -Wformat -Isrc -Ithird_party/imgui -Ithird_party/imgui/examples/libs/gl3w -Ithird_party/imgui/examples/opengl3_example`pkg-config --cflags glfw3`-c -o out/src/ktrace.o src/ktrace.c
Package glfw3 was not found in the pkg-config search path.
Perhaps you should add the directory containing`glfw3.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glfw3' found
src/ktrace.c: In function ‘evt_process_name’:
src/ktrace.c:531:9: warning: implicit declaration of function ‘strdup’ [-Wimplicit-function-declaration](%28track_t*%29oi->track)->name = strdup(name);
         ^
src/ktrace.c:531:37: warning: assignment makes pointer from integer without a cast [enabled by default](%28track_t*%29oi->track)->name = strdup(name);
                                     ^
src/ktrace.c: In function ‘evt_thread_name’:
src/ktrace.c:574:37: warning: assignment makes pointer from integer without a cast [enabled by default](%28track_t*%29oi->track)->name = strdup(tmp);
                                     ^
g++ -std=c++11 -MMD -g -Wall -Wformat -Isrc -Ithird_party/imgui -Ithird_party/imgui/examples/libs/gl3w -Ithird_party/imgui/examples/opengl3_example `pkg-config --cflags glfw3` -c -o out/src/main-opengl3.o src/main-opengl3.cpp
Package glfw3 was not found in the pkg-config search path.
Perhaps you should add the directory containing `glfw3.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glfw3' found
src/main-opengl3.cpp:14:24: fatal error: GLFW/glfw3.h: No such file or directory
 #include <GLFW/glfw3.h>
                        ^
compilation terminated.
make: **\* [out/src/main-opengl3.o] Error 1

**Comment by swetland** [comment]
Adjusted to use libsdl2 which is more widely available.  README updated with pre-reqs instructions.
